official_book_url:
  - https://amazon.com/dp/B09Y6RQSHM
start_url: https://www.royalroad.com/fiction/39408/beware-of-chicken/chapter/879865/interlude-day-at-the-beach
skip_urls:
  - https://www.royalroad.com/fiction/39408/beware-of-chicken/chapter/904526/notice-of-ama-and-removal-of-vol-1
metadata:
  title: Beware Of Chicken - Volume 3
  author: Casualfarmer
  description: |
    Jin Rou wanted to be a cultivator who defied the heavens, and surpassed all limits.
    
    Unfortunately for him, he died, and now I’m stuck here. Arrogant young masters? Heavenly tribulations? Cultivating for days on end, then getting into life or death battles?
    
    Yeah, no thanks. I'm getting out of here.
    
    In which a transmigrator decides that the only winning move is not to play.
files:
  cover_file: https://www.royalroadcdn.com/public/covers-large/beware-of-chicken-aacav1xoeg8.jpg
selectors:
  content_element: .chapter-content
  next_chapter_element: .nav-buttons a:-soup-contains("Next Chapter")
  title_element: .fic-header h1
