start_url: https://www.royalroad.com/fiction/29358/dungeon-crawler-carl-book-6-the-ghosts-of-earth/chapter/996463/book-6-prologue-chapter-198
metadata:
  title: 'Dungeon Crawler Carl Book 6: The Ghosts of Earth'
  author: DoctorHepa
  description: |
    The apocalypse will be televised!

    A man. His ex-girlfriend's cat. A sadistic game show unlike anything in the universe: a dungeon crawl where survival depends on killing your prey in the most entertaining way possible.

    In a flash, every human-erected construction on Earth—from Buckingham Palace to the tiniest of sheds—collapses in a heap, sinking into the ground.

    The buildings and all the people inside have all been atomized and transformed into the dungeon: an 18-level labyrinth filled with traps, monsters, and loot. A dungeon so enormous, it circles the entire globe.

    Only a few dare venture inside. But once you're in, you can't get out. And what's worse, each level has a time limit. You have but days to find a staircase to the next level down, or it's game over. In this game, it's not about your strength or your dexterity. It's about your followers, your views. Your clout. It's about building an audience and killing those goblins with style.

    You can't just survive here. You gotta survive big.

    You gotta fight with vigor, with excitement. You gotta make them stand up and cheer. And if you do have that "it" factor, you may just find yourself with a following. That's the only way to truly survive in this game—with the help of the loot boxes dropped upon you by the generous benefactors watching from across the galaxy.

    They call it Dungeon Crawler World. But for Carl, it's anything but a game.
files:
  cover_file: https://www.royalroadcdn.com/public/covers-full/29358-dungeon-crawler-carl.jpg
selectors:
  title_element: .fic-header h1
  content_element: .chapter-content
  next_chapter_element: .nav-buttons a:-soup-contains("Next Chapter")
