start_url: https://www.royalroad.com/fiction/26675/a-journey-of-black-and-red/chapter/393832/1-cruel-genesis
skip_urls:
  - https://www.royalroad.com/fiction/26675/a-journey-of-black-and-red/chapter/528917/glossary
metadata:
  title: A Journey of Black and Red
  author: Mecanimus
  description: |
    A conversation with a handsome stranger leaves Ariane chained in a cellar with a strange affliction. She soon discovers that the darkness of the nineteenth century’s Deep South hides many dangers. Mages, wolf shifters and the humans who hunt them play a risky game where to stumble is to die, all under the amused gaze of the apex predators of the supernatural world: vampires.

    It is never healthy to attract the gaze of the aristocracy of the night. It takes much to survive in this merciless world, but Ariane will not let that deter her. The southern belle has a bite, and she is willing to learn and to grow in this hostile new world. She will use whatever means necessary to reclaim her freedom, be it guile, charm, or those intriguing new instincts that make blood so delectable.
files:
  cover_file: https://www.royalroadcdn.com/public/covers-large/26675-a-journey-of-black-and-red.jpg
selectors:
  content_element: .chapter-content
  next_chapter_element: .nav-buttons a:-soup-contains("Next Chapter")
  title_element: .fic-header h1
skip_conversion: true
substitutions:
  - chapterUrl: https://www.royalroad.com/fiction/26675/a-journey-of-black-and-red/chapter/426349/34-ring-breaker
    selectorType: text
    selector: </p> <p>
    replaceWith: </p><p>
