officialBookUrl:
  - https://www.amazon.de/dp/B07RFN2ZMF
  - https://books2read.com/u/mZNkWJ
  - https://www.amazon.de/dp/B088N8CF62
  - https://books2read.com/u/mV8D7l
  - https://www.amazon.de/dp/B09BFZTNDM
  - https://books2read.com/u/bM7zGA
  - https://www.amazon.de/dp/B0B1YWPSH8
  - https://books2read.com/u/mV8D7l
startUrl: https://royalroad.com/fiction/14167/metaworld-chronicles/chapter/163574/chapter-1-some-things-begin-something-ends
skipUrls:
  - https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/171009/character-summaries
  - https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/179669/character-and-magic-summary-2
  - https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/202367/character-summary-3
  - https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/242718/character-summary-4
  - https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/401973/character-summary-5
  - https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/521452/character-summary-357
  - https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/309797/metaworld-spellcraft-glossary
  - https://www.royalroad.com/fiction/14167/metaworld-chronicles/chapter/501870/glossary
metadata:
  title: Metaworld Chronicles
  author: Wutosama
  description: |
    Gwen Song awoke in a world that was not her own, in which everything she was familiar with had been replaced. Instead of airplanes and electricity, this 21st-century Earth is ruled by magic and dragons; humanity survives in a land of magical beasts and otherworldly beings, protected by shielded enclaves and magical constructs.

    Follow Gwen across the world as she struggles to rebuild her life in this strange new reality. Behold a tale of adventure, friendship, and (of course), magic! Witness as she grows from a simple grade school student to a fully-fledged Mage, through university and beyond, discovering the secrets of a world made unreal by magic and mysticism.
files:
  coverFile: https://www.royalroadcdn.com/public/covers-large/14167-metaworld-chronicles.jpg
selectors:
  titleElement: .fic-header h1
  contentElement: .chapter-content
  nextChapterElement: .nav-buttons a:-soup-contains("Next Chapter")
removeEmptyElements: false
substitutions:
  - selectorType: regex
    selector: <p>.*<img.*>.*<\/p>
    replaceWith: <hr/>
