official_book_url:
  - https://www.amazon.de/dp/B09M2R6QLF
  - https://www.amazon.de/dp/B0B11L9TWP
  - https://www.amazon.de/dp/B0BCGMW45C
start_url: https://www.royalroad.com/fiction/21220/mother-of-learning/chapter/301778/1-good-morning-brother
end_url: https://www.royalroad.com/fiction/21220/mother-of-learning/chapter/455877/afterword
metadata:
  title: Mother of Learning
  author: nobody103
  description: |
    Zorian is a teenage mage of humble birth and slightly above-average skill, attending his third year of education at Cyoria's magical academy.
    He is a driven and irritable young man, consumed by a desire to ensure his own future and free himself of the influence of his family,
    whom he resents for favoring his brothers over him. Consequently, he has no time for pointless distractions or paying attention to other people's problems.
    As it happens, time is something he is about to get plenty of. On the eve of the Cyoria's annual summer festival,
    he is killed and brought back to the beginning of the month, just before he was about to take a train to Cyoria.
    Suddenly trapped in a time loop with no clear end or exit, Zorian will have to look both within and without to unravel the mystery before him.
    And he does have to unravel it, for the time loop hadn't been made for his sake and dangers lurk everywhere...
    Repetition is the mother of learning, but Zorian will have to first make sure he survives to try again - in a world of magic, even a time traveler isn't safe from those who wish him ill.
files:
  cover_file: https://www.royalroadcdn.com/public/covers-large/21220-mother-of-learning.jpg
selectors:
  content_element: .chapter-content
  next_chapter_element: .nav-buttons a:-soup-contains("Next Chapter")
  title_element: .fic-header h1
