startUrl: https://practicalguidetoevil.wordpress.com/2020/01/06/prologue-6/
endUrl: https://practicalguidetoevil.wordpress.com/2021/01/01/epilogue-6/
metadata:
  title: A Practical Guide to Evil - Book 6
  author: erraticerrata
  description: |
    The Empire stands triumphant.

    For twenty years the Dread Empress has ruled over the lands that were once the Kingdom of Callow, but behind the scenes of this dawning golden age threats to the crown are rising. The nobles of the Wasteland, denied the power they crave, weave their plots behind pleasant smiles. In the north the Forever King eyes the ever-expanding borders of the Empire and ponders war. The greatest danger lies to the west, where the First Prince of Procer has finally claimed her throne: her people sundered, she wonders if a crusade might not be the way to secure her reign. Yet none of this matters, for in the heart of the conquered lands the most dangerous man alive sat across an orphan girl and offered her a knife.

    Her name is Catherine Foundling, and she has a plan.
selectors:
  titleElement: .entry-title
  contentElement: .entry-content
  nextChapterElement: .nav-next a