official_book_url:
  - https://amazon.com/dp/B08SQD1DLR
  - https://amazon.com/dp/B092DQJNTT
  - https://amazon.com/dp/B098D3HJST
  - https://amazon.com/dp/B09BMPYZXF
  - https://amazon.com/dp/B09S3ZVK8L
  - https://amazon.com/dp/B09Y3GKGMW
  - https://amazon.com/dp/B0B4R3Q5PZ
  - https://amazon.com/dp/B0B8DDXHB8
start_url: https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/580224/0-advent
skip_urls:
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/593776/poll-which-blurb-is-the-best
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/612130/poll-volume-1-title
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/630572/announcement-patreon-update-follow-up-to-the-poll
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/629992/important-patreon-poll-please-respond-honestly
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/617838/poll-cover-art
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/613672/salvos-vol-1-curious-beginnings-now-live-on-amazon
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/612610/poll-last-title-poll
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/668780/announcement
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/663950/a-demons-pride-salvos-volume-2-is-now-live-on
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/699849/announcement-salvos-vol-1-now-available-as-an
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/726582/salvos-volume-3-now-available-on-amazon
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/802279/another-announcement
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/799011/double-announcement
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/811289/have-art
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/814666/quick-little-covid-update
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/837146/quick-update-here-is-the-surprise
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/840609/new-cover-very-quick-update
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/846299/salvos-volume-3s-audiobook-is-now-available-on
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/683858/reminder-for-this-week
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/847612/official-salvos-merchandise
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/856306/salvos-volume-5-part-1-corruption-and-centinels
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/760258/200-special-side-character-popularity-poll
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/674514/a-witch-and-a-demon-walk-into-a
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/866508/chapter-300-special-salvos-side-character-popularity
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/889932/salvos-german-translation-is-officially-available
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/919339/grand-skill-book-6-is-now-available-on-amazon
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/921906/new-fic-announcement-violet-not-a-chapter
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/939533/not-a-chapter-some-introspection-after-a-year
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/947959/not-a-chapter-deleting-commenting-rules-quick
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/952469/quick-update-something-is-coming
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/955549/new-fic-announcement-thera-not-a-chapter
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/961857/salvos-book-7-is-now-available-on-amazon-also
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/963346/salvos-webtoon-pre-emptive-announcement-patreon
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/967218/salvos-volume-4-audiobook-is-now-available
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/968326/chapter-400-special-side-character-popularity
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/994517/salvos-volume-2-part-1s-german-edition-is-now
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/996090/salvos-book-1-currently-free-on-amazon
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/1003096/salvos-book-5-corruption-and-centinels-is-now
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/1006844/salvos-book-8-is-now-available-on-the-amazon-store
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/1016455/salvos-german-translation-book-3-is-up
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/1029959/announcement-patreon-now-at-30-chapters-ahead
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/1034300/sick-another-webcomic-preview
  - https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/1041180/new-salvos-german-edition-out-now
  - https://www.royalroad.com/fiction/37438/the-hellprinces-salvos-a-monster-evolution-litrpg/chapter/1050362/i-messed-up-webcomic-arts
  - https://www.royalroad.com/fiction/37438/the-hellprinces-salvos-a-monster-evolution-litrpg/chapter/1063955/new-salvos-german-edition-out-again-check-it-out
  - https://www.royalroad.com/fiction/37438/hellprinces-salvos-a-monster-evolution-litrpg/chapter/1069645/new-fic-announcement-amelia-the-level-zero-hero
metadata:
  title: Salvos
  author: MelasDelta
  description: |
    The life of an Infant Demon is a bloody grind to the top. For Salvos, a curious newborn Demon with a penchant for making friends, surviving the swarms of wild Demons in the Netherworld was always going to be a difficult task. She will adapt, gain experience, and evolve to survive this hellish landscape with the help of her sole companion.

    But when her companion's life is threatened by a mysterious Demon King, she'll have to do what it takes to save him. Even if it means separating from him and being tossed into an unfamiliar world with Humans, monsters, and a bright blue sky where she is scorned for being born a Demon.

    However, the law of evolution is survival of the fittest, and no matter where she is, Salvos will survive.
selectors:
  content_element: .chapter-content
  next_chapter_element: .nav-buttons a:-soup-contains("Next Chapter")
  title_element: .fic-header h1
  cutOffElement:
    - blockquote:-soup-contains("Author's Note:")
    - blockquote:-soup-contains("Author's Notes:")
    - p:-soup-contains("Author's Note:")
    - p:-soup-contains("Author's Notes:")
files:
  cover_file: https://www.royalroadcdn.com/public/covers-large/37438-salvos-a-monster-evolution-litrpg.jpg?time=1662541652
substitutions:
  - selectorType: text
    selector: —--
    replaceWith: <hr/>
  - selector_type: css
    selector: .chapter-content hr:first-child
  - selector_type: css
    selector: ".chapter-content p[style='text-align: center']:first-child"
  - chapter_url: https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/647214/76-refinement
    selector_type: text
    selector: "(Author’s Note: I may or may not have been projecting through Daniel here. I had been suffering from major jet lag when I wrote this a month ago.)"
  - chapter_url: https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/804233/244-nightsveil-part-4
    selector_type: css
    selector: 'p:-soup-contains("Disclaimer: This chapter is written in an experimental style.")'
  - chapter_url: https://www.royalroad.com/fiction/37438/salvos-a-monster-evolution-litrpg/chapter/804233/244-nightsveil-part-4
    selector_type: css
    selector: p:-soup-contains("I already know some of y'all are gonna complain about the experimental style.")