start_url: https://tiraas.net/2014/08/20/book-1-prologue/
end_url: https://tiraas.net/2020/10/06/bonus-65-the-girl-from-everywhere-part-2/
metadata:
  title: The Gods are Bastards
  author: D. D. Webb
  description: |
    Evil is rising.

    In an isolated frontier town, a group of new students arrive at the University which will train them to fulfill their heroic destinies.  Unfortunately, they quickly prove to be more of a threat to each other than the machinations of the resurgent Demon Queen.

    In Tiraas, the Imperial capital, that same queen’s schemes spark off confrontations between the powers of the Empire, the Universal Church, and multiple other factions, each plotting for a slice of the pie.  Where all these powers meet, one man is positioned to be crushed beneath them, or to seize the ultimate advantage–if he proves capable.

    Evil is rising, and no one is ready…
selectors:
  title_element: .entry-title
  content_element: .entry-content
  next_chapter_element: .entry-content a:-soup-contains("Next Chapter")
  cut_off_element: p:has(a:-soup-contains("Next Chapter")), p:has(a:-soup-contains("Previous Chapter"))