official_book_url:
  - https://amazon.com/dp/B08WL8CS8B
  - https://amazon.com/dp/B09HN7BHZJ
  - https://amazon.com/dp/B09NPBL57X
start_url: https://www.royalroad.com/fiction/36735/the-perfect-run/chapter/569225/1-quicksave
end_url: https://www.royalroad.com/fiction/36735/the-perfect-run/chapter/767650/130-farewell-new-rome-ending
metadata:
  title: The Perfect Run
  author: Maxime J. Durand (Void Herald)
  description: |
    Ryan "Quicksave" Romano is an eccentric adventurer with a strange power: he can create a save-point in time and redo his life whenever he dies. Arriving in New Rome, the glitzy capital of sin of a rebuilding Europe, he finds the city torn between mega-corporations, sponsored heroes, superpowered criminals, and true monsters. It's a time of chaos, where potions can grant the power to rule the world and dangers lurk everywhere. 
    
    Ryan only sees different routes; and from Hero to Villain, he has to try them all. Only then will he achieve his perfect ending... no matter how many loops it takes.
files:
  cover_file: https://www.royalroadcdn.com/public/covers-large/36735-the-perfect-run.jpg?time=1604749383
selectors:
  content_element: .chapter-content
  next_chapter_element: .nav-buttons a:-soup-contains("Next Chapter")
  title_element: .fic-header h1
