start_url: https://wanderinginn.com/2021/01/10/8-00/
end_url: https://wanderinginn.com/2022/05/03/epilogue/
metadata:
  title: The Wandering Inn - Volume 8
  author: pirateaba
  description: |
    "No killing Goblins."

    So reads the sign outside of the Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.

    It's a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a dragon. She doesn't belong in a place where monster attacks are a fact of life, and where humans are one species among many. But she must adapt to her new life. Or die.

    In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no [Warrior], no [Mage]. Erin Solstice runs an inn.

    She's an [Innkeeper].
selectors:
  title_element: .entry-title
  content_element: .entry-content
  next_chapter_element: .entry-content a:-soup-contains("Next Chapter")
  cut_off_element:
    - p:-soup-contains("After Chapter Thoughts:")
    - p:-soup-contains("After Chapter Notes:")
    - p:-soup-contains("Author’s Story:")
    - p:-soup-contains("Author’s Note:")
    - p:-soup-contains("Author’s Notes:")
    - p:-soup-contains("Author’s Thoughts:")
    - p:-soup-contains("Author Breakdown:")
    - p:has(a:-soup-contains("Previous Chapter"))
    - p:has(a:-soup-contains("Next Chapter"))
substitutions:
  - selector_type: text
    selector: <p>—-</p>
    replace_with: <hr/>
  - selector_type: text
    selector: <p>—–</p>
    replace_with: <hr/>
  - selector_type: text
    selector: <p>——</p>
    replace_with: <hr/>
  - chapter_url: https://wanderinginn.com/2021/01/10/8-00/
    selector_type: css
    selector: p:-soup-contains("Andrea Parsneau, MouthyMaven")
  - chapter_url: https://wanderinginn.com/2021/01/13/8-01/
    selector_type: css
    selector: p:-soup-contains("One of The Wandering Inn’s readers")
  - chapter_url: https://wanderinginn.com/2021/01/27/8-04-t/
    selector_type: css
    selector: p:-soup-contains("The author is on their monthly break")
  - chapter_url: https://wanderinginn.com/2021/02/07/8-05-i/
    selector_type: css
    selector: p:-soup-contains("Trigger Warning.")
  - chapter_url: https://wanderinginn.com/2021/02/10/8-06-rt/
    selector_type: css
    selector: p:-soup-contains("Flowers of Esthelm, Book 3 of The Wandering Inn")
  - chapter_url: https://wanderinginn.com/2021/02/14/8-07-l/
    selector_type: css
    selector: p:-soup-contains("Flowers of Esthelm, Book 3 of The Wandering Inn")
  - chapter_url: https://wanderinginn.com/2021/02/17/8-08-j/
    selector_type: css
    selector: p:-soup-contains("Flowers of Esthelm, Book 3 of The Wandering Inn")
  - chapter_url: https://wanderinginn.com/2021/02/21/8-09/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is going to be working with editors")
  - chapter_url: https://wanderinginn.com/2021/02/24/8-10/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is going to be working with editors")
  - chapter_url: https://wanderinginn.com/2021/02/24/8-10/
    selector_type: css
    selector: p:-soup-contains("Also, the author is on break until March 6th")
  - chapter_url: https://wanderinginn.com/2021/03/14/interlude-the-rower-and-the-bartender/
    selector_type: css
    selector: p:-soup-contains("Trigger Warning.")
  - chapter_url: https://wanderinginn.com/2021/03/17/8-13-f/
    selector_type: css
    selector: p:-soup-contains("On Sunday, 6 PM EST, Rebecca Brewer")
  - chapter_url: https://wanderinginn.com/2021/03/21/8-14-n/
    selector_type: css
    selector: p:-soup-contains("The author is on break")
  - chapter_url: https://wanderinginn.com/2021/03/21/8-14-n/
    selector_type: css
    selector: p:-soup-contains("Rebecca Brewer, the editor who worked on 8.11 E")
  - chapter_url: https://wanderinginn.com/2021/03/21/8-14-n/
    selector_type: css
    selector: p:-soup-contains("Also, she has done an interview with The Fantasy Inn!")
  - chapter_url: https://wanderinginn.com/2021/03/30/8-15/
    selector_type: css
    selector: p:-soup-contains("Iron Prince by Bryce O’Conner")
  - chapter_url: https://wanderinginn.com/2021/04/04/interlude-paradigm-shift-pt-1/
    selector_type: css
    selector: p:-soup-contains("Enuryn the [Naturalist] has opened an online store")
  - chapter_url: https://wanderinginn.com/2021/04/10/8-16/
    selector_type: css
    selector: p:-soup-contains("Podium Publishing is offering a TWI-embossed frying pan giveaway")
  - chapter_url: https://wanderinginn.com/2021/04/13/8-17-h/
    selector_type: css
    selector: p:-soup-contains("Podium Publishing is offering a TWI-embossed frying pan giveaway")
  - chapter_url: https://wanderinginn.com/2021/04/13/8-17-h/
    selector_type: css
    selector: p:-soup-contains("Also, I am taking my break early due to getting the vaccine shot")
  - chapter_url: https://wanderinginn.com/2021/04/25/8-18-h/
    selector_type: css
    selector: p:-soup-contains("The Flowers of Esthelm, Book 3 of The Wandering Inn is out on Audible!")
  - chapter_url: https://wanderinginn.com/2021/04/28/8-19-h/
    selector_type: css
    selector: p:-soup-contains("The Flowers of Esthelm, Book 3 of The Wandering Inn is out on Audible!")
  - chapter_url: https://wanderinginn.com/2021/05/04/8-21-l/
    selector_type: css
    selector: p:-soup-contains("I am taking a 1-update break")
  - chapter_url: https://wanderinginn.com/2021/05/19/8-23/
    selector_type: css
    selector: p:-soup-contains("The author is taking their monthly break!")
  - chapter_url: https://wanderinginn.com/2021/06/12/8-27/
    selector_type: css
    selector: p:-soup-contains("The next Public chapter will be released on June 22nd")
  - chapter_url: https://wanderinginn.com/2021/06/26/interlude-the-pets-of-innworld/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is on break!")
  - chapter_url: https://wanderinginn.com/2021/07/18/8-31/
    selector_type: text
    selector: <p class="western">—-</p>
    replace_with: <hr/>
  - chapter_url: https://wanderinginn.com/2021/07/18/8-31/
    selector_type: css
    selector: p:-soup-contains("Side story chapter AND edited chapter are delayed due to…Windows Update.")
  - chapter_url: https://wanderinginn.com/2021/07/20/interlude-pisces-revised/
    selector_type: css
    selector: p:-soup-contains("Trigger Warning")
  - chapter_url: https://wanderinginn.com/2021/07/25/8-32/
    selector_type: css
    selector: p:-soup-contains("It is the 5th Anniversary of The Wandering Inn")
  - chapter_url: https://wanderinginn.com/2021/07/25/8-32/
    selector_type: css
    selector: p:-soup-contains("The Last Tide is going to launch a Kickstarter on August 24th")
  - chapter_url: https://wanderinginn.com/2021/07/28/8-33-r/
    selector_type: css
    selector: p:-soup-contains("It is the 5th Anniversary of The Wandering Inn")
  - chapter_url: https://wanderinginn.com/2021/08/04/8-35/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is on its monthly week-long break!")
  - chapter_url: https://wanderinginn.com/2021/08/04/8-35/
    selector_type: css
    selector: p:-soup-contains("Editor Contest Announcement")
  - chapter_url: https://wanderinginn.com/2021/08/15/8-36-h/
    selector_type: css
    selector: p:-soup-contains("The Facebook Gamelit Society")
  - chapter_url: https://wanderinginn.com/2021/08/15/8-36-h/
    selector_type: css
    selector: p:-soup-contains("The Kickstarter for The Last Tide will be on the 24th of August!")
  - chapter_url: https://wanderinginn.com/2021/08/17/8-37-h/
    selector_type: css
    selector: p:nth-of-type(-n + 4)
  - chapter_url: https://wanderinginn.com/2021/08/22/8-38-h/
    selector_type: css
    selector: p:-soup-contains("The Last Tide")
  - chapter_url: https://wanderinginn.com/2021/08/24/8-39/
    selector_type: css
    selector: p:has(a)
  - chapter_url: https://wanderinginn.com/2021/08/24/8-39/
    selector_type: css
    selector: p:nth-of-type(-n + 9)
  - chapter_url: https://wanderinginn.com/2021/09/04/8-41/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn will be on break")
  - chapter_url: https://wanderinginn.com/2021/09/26/8-44-o/
    selector_type: css
    selector: p:-soup-contains("I did another interview")
  - chapter_url: https://wanderinginn.com/2021/10/03/8-46-g/
    selector_type: css
    selector: p:-soup-contains("Barbara Clark will edit a chapter in October!")
  - chapter_url: https://wanderinginn.com/2021/10/06/interlude-perspective-and-past/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is on its monthly break")
  - chapter_url: https://wanderinginn.com/2021/11/03/interlude-conversations/
    selector_type: css
    selector: p:-soup-contains("The author is on break until the 13th of November for Patrons!")
  - chapter_url: https://wanderinginn.com/2021/11/17/8-52-mn/
    selector_type: css
    selector: p:-soup-contains("See that header up top? Book 5 on Audible.")
  - chapter_url: https://wanderinginn.com/2021/11/17/8-52-mn/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn now has a fan-podcast!")
  - chapter_url: https://wanderinginn.com/2021/11/21/8-53-fh/
    selector_type: css
    selector: p:-soup-contains("See that header up top? Book 5 on Audible.")
  - chapter_url: https://wanderinginn.com/2021/11/21/8-53-fh/
    selector_type: css
    selector: p:-soup-contains("I am on break until the 30th for Patrons")
  - chapter_url: https://wanderinginn.com/2021/12/05/8-55-l/
    selector_type: css
    selector: p:-soup-contains("Mother of Learning is out on Amazon!")
  - chapter_url: https://wanderinginn.com/2021/12/15/8-58-pfh/
    selector_type: css
    selector: p:-soup-contains("I am taking a ~mysterious break~")
  - chapter_url: https://wanderinginn.com/2021/12/26/8-60/
    selector_type: css
    selector: p:-soup-contains("This chapter is out, as is customary for Patreons and Public readers!")
  - chapter_url: https://wanderinginn.com/2021/12/29/8-61/
    selector_type: css
    selector: p:-soup-contains("The story is on break until January 15th")
  - chapter_url: https://wanderinginn.com/2022/01/16/8-62-k/
    selector_type: css
    selector: p:-soup-contains("No Killing Goblins, a The Wandering Inn podcast")
  - chapter_url: https://wanderinginn.com/2022/01/16/8-62-k/
    selector_type: css
    selector: a:-soup-contains("Podomatic")
  - chapter_url: https://wanderinginn.com/2022/01/16/8-62-k/
    selector_type: css
    selector: a:-soup-contains("Apple")
  - chapter_url: https://wanderinginn.com/2022/01/16/8-62-k/
    selector_type: css
    selector: a:-soup-contains("Google")
  - chapter_url: https://wanderinginn.com/2022/01/30/8-65/
    selector_type: css
    selector: p:-soup-contains("The author is on break until the 8th of February!")
  - chapter_url: https://wanderinginn.com/2022/02/13/interlude-hectval-pt-2/
    selector_type: css
    selector: p:-soup-contains("I am delighted to shout out fellow author Selkie Myth")
  - chapter_url: https://wanderinginn.com/2022/02/23/8-66/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is conducting a 2022 survey!")
  - chapter_url: https://wanderinginn.com/2022/02/27/8-67/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is conducting a 2022 survey!")
  - chapter_url: https://wanderinginn.com/2022/02/27/8-67/
    selector_type: css
    selector: p:-soup-contains("The author is on break until March 8th!")
  - chapter_url: https://wanderinginn.com/2022/03/09/8-68/
    selector_type: css
    selector: p:-soup-contains("Trigger Warning")
  - chapter_url: https://wanderinginn.com/2022/03/09/8-68/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn now has a fanmail and business email!")
  - chapter_url: https://wanderinginn.com/2022/03/09/8-68/
    selector_type: css
    selector: p:-soup-contains("Have you filled out the survey?")
  - chapter_url: https://wanderinginn.com/2022/03/18/8-75/
    selector_type: css
    selector: p:-soup-contains("The author is now on a break")
  - chapter_url: https://wanderinginn.com/2022/03/30/8-77-b/
    selector_type: css
    selector: p:-soup-contains("The author is on break")
  - chapter_url: https://wanderinginn.com/2022/04/17/8-80/
    selector_type: css
    selector: p:-soup-contains("Book 6, The General of Izril is available")
  - chapter_url: https://wanderinginn.com/2022/04/20/8-81/
    selector_type: css
    selector: p:-soup-contains("Book 6, The General of Izril is available")
  - chapter_url: https://wanderinginn.com/2022/04/20/8-81/
    selector_type: css
    selector: p:-soup-contains("I am taking a small delay of one update")
  - chapter_url: https://wanderinginn.com/2022/04/26/8-82-pt-1/
    selector_type: css
    selector: p:-soup-contains("The final chapter will be released on May 3rd")
  - chapter_url: https://wanderinginn.com/2022/04/26/8-82-pt-1/
    selector_type: css
    selector: p:-soup-contains("Podium is hosting an apron giveaway!")
  - chapter_url: https://wanderinginn.com/2022/05/03/8-83/
    selector_type: css
    selector: p:-soup-contains("Casualfarmer has released their first novel")
