start_url: https://wanderinginn.com/2022/06/03/9-00/
skip_urls:
  - https://wanderinginn.com/2022/07/24/the-wandering-inn-ama/
crawler_module: WanderingInnPatreonCrawler
metadata:
  title: The Wandering Inn - Volume 9
  author: pirateaba
  description: |
    "No killing Goblins."

    So reads the sign outside of the Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.

    It's a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a dragon. She doesn't belong in a place where monster attacks are a fact of life, and where humans are one species among many. But she must adapt to her new life. Or die.

    In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no [Warrior], no [Mage]. Erin Solstice runs an inn.

    She's an [Innkeeper].
selectors:
  title_element: .entry-title
  content_element: .entry-content
  next_chapter_element: .entry-content a:-soup-contains("Next Chapter")
  cut_off_element:
    - p:-soup-contains("After Chapter Thoughts:")
    - p:-soup-contains("After Chapter Notes:")
    - p:-soup-contains("Author’s Story:")
    - p:-soup-contains("Author’s Note:")
    - p:-soup-contains("Author’s Notes:")
    - p:-soup-contains("Author’s Thoughts:")
    - p:has(a:-soup-contains("Previous Chapter"))
    - p:has(a:-soup-contains("Next Chapter"))
substitutions:
  - selector_type: text
    selector: <p>—-</p>
    replace_with: <hr/>
  - selector_type: text
    selector: <p>—–</p>
    replace_with: <hr/>
  - selector_type: text
    selector: <p>——</p>
    replace_with: <hr/>
  - chapter_url: https://wanderinginn.com/2022/06/18/interlude-singing-ships/
    selector_type: css
    selector: p:-soup-contains("I am on break until the 28th for Patrons!")
  - chapter_url: https://wanderinginn.com/2022/06/28/9-03/
    selector_type: css
    selector: p:-soup-contains("What could this mean? Click here to learn about a free sweepstakes!")
  - chapter_url: https://wanderinginn.com/2022/07/02/9-04/
    selector_type: css
    selector: p:-soup-contains("Check out this link for an announcement")
  - chapter_url: https://wanderinginn.com/2022/07/02/9-04/
    selector_type: css
    selector: p:-soup-contains("I will be doing an AMA")
  # - chapter_url: https://wanderinginn.com/2022/07/05/interlude-the-isles-of-goblin-and-minos/
  #   selector_type: text
  #   selector: <p><strong>*🐁 If you haven’t read Haldagaz and Rhata’s mini-chapters, go to Interlude &#8211; Hectval Pt. 2 and find them!</strong></p>
  #   replace_with: <hr/>
  - chapter_url: https://wanderinginn.com/2022/07/19/9-08/
    selector_type: css
    selector: p:-soup-contains("The author is on break until July 30th!")
  - chapter_url: https://wanderinginn.com/2022/07/30/interlude-mundanity-and-memorials/
    selector_type: css
    selector: p:-soup-contains("Firebrand is a new story by a friend of mine, Quill!")
  - chapter_url: https://wanderinginn.com/2022/08/06/interlude-the-competition/
    selector_type: css
    selector: p:-soup-contains("The author is on an actual vacation for once")
  # TODO: https://wanderinginn.com/2022/08/20/9-09-p/ filter vacation report
  - chapter_url: https://wanderinginn.com/2022/09/10/9-15-vm/
    selector_type: css
    selector: p:-soup-contains("I am on break until the 20th of September!")
  - chapter_url: https://wanderinginn.com/2022/09/28/interlude-the-great-race/
    selector_type: css
    selector: p:-soup-contains("I wrote an essay because")
  - chapter_url: https://wanderinginn.com/2022/09/28/interlude-the-great-race/
    selector_type: css
    selector: p:-soup-contains("https://wanderinginn.com/essay-ais-and-the-future-of-writing/")
  - chapter_url: https://wanderinginn.com/2022/10/09/9-19/
    selector_type: css
    selector: p:-soup-contains("Andrew Rowe has come out with Book 4 in his series, Arcane Ascension!")
  - chapter_url: https://wanderinginn.com/2022/10/16/interlude-death-and-stitches/
    selector_type: css
    selector: p:-soup-contains("The Merch Store has Halloween-themed merchandise!")
  - chapter_url: https://wanderinginn.com/2022/10/16/interlude-death-and-stitches/
    selector_type: css
    selector: p a img
  - chapter_url: https://wanderinginn.com/2022/10/16/interlude-death-and-stitches/
    selector_type: css
    selector: p:-soup-contains("Book 8, Blood of Liscor, is coming out on Audible and as an e-book soon!")
  - chapter_url: https://wanderinginn.com/2022/10/16/interlude-death-and-stitches/
    selector_type: css
    selector: p:-soup-contains("The author is on break until October 25!")
  - chapter_url: https://wanderinginn.com/2022/10/26/9-21/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn survey has a statistics page!")
  - chapter_url: https://wanderinginn.com/2022/10/30/9-22-gn/
    selector_type: css
    selector: p:-soup-contains("Trigger Warning")
  - chapter_url: https://wanderinginn.com/2022/11/02/9-23-ggggggggg/
    selector_type: css
    selector: p:-soup-contains("Trigger Warning")
  - chapter_url: https://wanderinginn.com/2022/11/05/9-24/
    selector_type: css
    selector: p:-soup-contains("Author’s Disclaimer:")
  - chapter_url: https://wanderinginn.com/2022/11/16/interlude-adventurers-pt-3/
    selector_type: css
    selector: p:-soup-contains("Join a free gift raffle for Blood of Liscor, the next book on Audible!")
  - chapter_url: https://wanderinginn.com/2022/11/16/interlude-adventurers-pt-3/
    selector_type: css
    selector: p:-soup-contains("The author is on break until November 26th!")
  - chapter_url: https://wanderinginn.com/2022/11/27/9-25/
    selector_type: css
    selector: p:-soup-contains("The Merch Store is having a Black Friday sale!")
  - chapter_url: https://wanderinginn.com/2022/11/27/9-25/
    selector_type: css
    selector: p:-soup-contains("The Blood of Liscor, Book 8 is out on Audible and as an e-book!")
  - chapter_url: https://wanderinginn.com/2022/11/29/9-26-f/
    selector_type: css
    selector: p:-soup-contains("Gravesong is out now on Yonder!")
  - chapter_url: https://wanderinginn.com/2022/12/04/9-27-rc/
    selector_type: css
    selector: p:-soup-contains("Gravesong is out now on Yonder!")
  - chapter_url: https://wanderinginn.com/2022/12/18/9-29/
    selector_type: css
    selector: p:-soup-contains("This chapter is 45,000+ words long.")
  - chapter_url: https://wanderinginn.com/2022/12/21/9-30/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn store is having a Solstice sale!")
  - chapter_url: https://wanderinginn.com/2022/12/21/9-30/
    selector_type: css
    selector: p:-soup-contains("Trial of the Alchemist, a mystery-fantasy by Trevor Melanson")
  - chapter_url: https://wanderinginn.com/2022/12/25/9-31/
    selector_type: css
    selector: p:-soup-contains("The author is on break until January 17th!")
  - chapter_url: https://wanderinginn.com/2023/01/31/9-35-o/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is putting out an open-call for a book marketer/publicist!")
  - chapter_url: https://wanderinginn.com/2023/02/04/9-36-ho/
    selector_type: css
    selector: p:-soup-contains("I am taking two updates off to finish my rewrite of Volume 1.")
  - chapter_url: https://wanderinginn.com/2023/02/15/9-37-ho/
    selector_type: css
    selector: p:-soup-contains("I am on my monthly break!")
