startUrl: https://wanderinginn.com/2022/06/03/9-00/
skipUrls:
  - https://wanderinginn.com/2022/07/24/the-wandering-inn-ama/
crawlerModule: WanderingInnPatreonCrawler
metadata:
  title: The Wandering Inn - Volume 9
  author: pirateaba
  description: |
    "No killing Goblins."

    So reads the sign outside of the Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.

    It's a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a dragon. She doesn't belong in a place where monster attacks are a fact of life, and where humans are one species among many. But she must adapt to her new life. Or die.

    In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no [Warrior], no [Mage]. Erin Solstice runs an inn.

    She's an [Innkeeper].
selectors:
  titleElement: .entry-title
  contentElement: .entry-content
  nextChapterElement: .entry-content a:-soup-contains("Next Chapter")
  cutOffElement:
    - p:-soup-contains("After Chapter Thoughts:")
    - p:-soup-contains("After Chapter Notes:")
    - p:-soup-contains("Author’s Story:")
    - p:-soup-contains("Author’s Note:")
    - p:-soup-contains("Author’s Notes:")
    - p:-soup-contains("Author’s Thoughts:")
    - p:has(a:-soup-contains("Previous Chapter"))
    - p:has(a:-soup-contains("Next Chapter"))
substitutions:
  - selectorType: text
    selector: <p>—-</p>
    replaceWith: <hr/>
  - selectorType: text
    selector: <p>—–</p>
    replaceWith: <hr/>
  - selectorType: text
    selector: <p>——</p>
    replaceWith: <hr/>
  - chapterUrl: https://wanderinginn.com/2022/06/18/interlude-singing-ships/
    selectorType: css
    selector: p:-soup-contains("I am on break until the 28th for Patrons!")
  - chapterUrl: https://wanderinginn.com/2022/06/28/9-03/
    selectorType: css
    selector: p:-soup-contains("What could this mean? Click here to learn about a free sweepstakes!")
  - chapterUrl: https://wanderinginn.com/2022/07/02/9-04/
    selectorType: css
    selector: p:-soup-contains("Check out this link for an announcement")
  - chapterUrl: https://wanderinginn.com/2022/07/02/9-04/
    selectorType: css
    selector: p:-soup-contains("I will be doing an AMA")
  # - chapterUrl: https://wanderinginn.com/2022/07/05/interlude-the-isles-of-goblin-and-minos/
  #   selectorType: text
  #   selector: <p><strong>*🐁 If you haven’t read Haldagaz and Rhata’s mini-chapters, go to Interlude &#8211; Hectval Pt. 2 and find them!</strong></p>
  #   replaceWith: <hr/>
  - chapterUrl: https://wanderinginn.com/2022/07/19/9-08/
    selectorType: css
    selector: p:-soup-contains("The author is on break until July 30th!")
  - chapterUrl: https://wanderinginn.com/2022/07/30/interlude-mundanity-and-memorials/
    selectorType: css
    selector: p:-soup-contains("Firebrand is a new story by a friend of mine, Quill!")
  - chapterUrl: https://wanderinginn.com/2022/08/06/interlude-the-competition/
    selectorType: css
    selector: p:-soup-contains("The author is on an actual vacation for once")
  # TODO: https://wanderinginn.com/2022/08/20/9-09-p/ filter vacation report
  - chapterUrl: https://wanderinginn.com/2022/09/10/9-15-vm/
    selectorType: css
    selector: p:-soup-contains("I am on break until the 20th of September!")
  - chapterUrl: https://wanderinginn.com/2022/09/28/interlude-the-great-race/
    selectorType: css
    selector: p:-soup-contains("I wrote an essay because")
  - chapterUrl: https://wanderinginn.com/2022/09/28/interlude-the-great-race/
    selectorType: css
    selector: p:-soup-contains("https://wanderinginn.com/essay-ais-and-the-future-of-writing/")
