startUrl: https://wanderinginn.com/2019/03/19/6-00/
endUrl: https://wanderinginn.com/2020/01/01/6-68/
metadata:
  title: The Wandering Inn - Volume 6
  author: pirateaba
  description: |
    "No killing Goblins."

    So reads the sign outside of the Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.

    It's a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a dragon. She doesn't belong in a place where monster attacks are a fact of life, and where humans are one species among many. But she must adapt to her new life. Or die.

    In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no [Warrior], no [Mage]. Erin Solstice runs an inn.

    She's an [Innkeeper].
selectors:
  titleElement: .entry-title
  contentElement: .entry-content
  nextChapterElement: .entry-content a:-soup-contains("Next Chapter")
  cutOffElement: p:has(a:-soup-contains("Next Chapter"))
substitutions:
  - selectorType: text
    selector: <p>—-</p>
    replaceWith: <hr/>
  - chapterUrl: https://wanderinginn.com/2019/05/07/6-14-k/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/05/11/6-15-k/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/07/02/interlude-embria/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/08/03/interlude-numbtongue-pt-2/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/08/10/6-36-e/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/08/27/6-41-e/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/08/31/interlude-two-rats/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/09/07/6-42-e/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/09/10/6-43-e/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2019/09/14/6-44-e/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/01/01/6-68/
    selectorType: css
    selector: p:first-of-type
