start_url: https://wanderinginn.com/2022/06/03/9-00/
skip_urls:
  - https://wanderinginn.com/2022/07/24/the-wandering-inn-ama/
  - https://wanderinginn.com/2023/05/01/may-2023-break/
  - https://wanderinginn.com/2023/08/02/writing-update-warsong/
  - https://wanderinginn.com/2023/08/15/warsong-update/
  - https://wanderinginn.com/2023/08/26/no-chapter-on-the-26th/
crawler_module: WanderingInnPatreonCrawler
metadata:
  title: The Wandering Inn - Volume 9
  author: pirateaba
  description: |
    "No killing Goblins."

    So reads the sign outside of the Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.

    It's a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a dragon. She doesn't belong in a place where monster attacks are a fact of life, and where humans are one species among many. But she must adapt to her new life. Or die.

    In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no [Warrior], no [Mage]. Erin Solstice runs an inn.

    She's an [Innkeeper].
selectors:
  title_element: .entry-title
  content_element: .entry-content
  next_chapter_element: span.nav-next a[rel=next]
  cut_off_element:
    - p:-soup-contains("After Chapter Thoughts:")
    - p:-soup-contains("After Chapter Notes:")
    - p:-soup-contains("Author Call:")
    - p:-soup-contains("Author’s Story:")
    - p:-soup-contains("Author’s Note:")
    - p:-soup-contains("Author’s Notes:")
    - p:-soup-contains("Author’s Thoughts:")
    - p:-soup-contains("Author’s Note")
    - p:-soup-contains("Authors’ Note:")
    # For https://wanderinginn.com/2023/10/03/interlude-the-library/
    - p:-soup-contains("These are only a few of the amazing Inktober art pieces coming out of the Discord")
    # These two should alwas be at the end of the list!
    - p:has(a:-soup-contains("Previous Chapter"))
    - p:has(a:-soup-contains("Next Chapter"))
style: |
  @font-face {
    font-family: "Charm";
    src: url("./charm.ttf") format("truetype");
    font-weight: 400;
    font-style: normal;
    font-display: swap;
  }
  .mrsha-write {
      font-family: "Charm", cursive;
      font-size: 110%;
      letter-spacing: 0.12rem;
  }
substitutions:
  - selector_type: text
    selector: <p>—-</p>
    replace_with: <hr/>
  - selector_type: text
    selector: <p>—–</p>
    replace_with: <hr/>
  - selector_type: text
    selector: <p>——</p>
    replace_with: <hr/>
  - chapter_url: https://wanderinginn.com/2022/06/18/interlude-singing-ships/
    selector_type: css
    selector: p:-soup-contains("I am on break until the 28th for Patrons!")
  - chapter_url: https://wanderinginn.com/2022/06/28/9-03/
    selector_type: css
    selector: p:-soup-contains("What could this mean? Click here to learn about a free sweepstakes!")
  - chapter_url: https://wanderinginn.com/2022/07/02/9-04/
    selector_type: css
    selector: p:-soup-contains("Check out this link for an announcement")
  - chapter_url: https://wanderinginn.com/2022/07/02/9-04/
    selector_type: css
    selector: p:-soup-contains("I will be doing an AMA")
  # - chapter_url: https://wanderinginn.com/2022/07/05/interlude-the-isles-of-goblin-and-minos/
  #   selector_type: text
  #   selector: <p><strong>*🐁 If you haven’t read Haldagaz and Rhata’s mini-chapters, go to Interlude &#8211; Hectval Pt. 2 and find them!</strong></p>
  #   replace_with: <hr/>
  - chapter_url: https://wanderinginn.com/2022/07/19/9-08/
    selector_type: css
    selector: p:-soup-contains("The author is on break until July 30th!")
  - chapter_url: https://wanderinginn.com/2022/07/30/interlude-mundanity-and-memorials/
    selector_type: css
    selector: p:-soup-contains("Firebrand is a new story by a friend of mine, Quill!")
  - chapter_url: https://wanderinginn.com/2022/08/06/interlude-the-competition/
    selector_type: css
    selector: p:-soup-contains("The author is on an actual vacation for once")
  # TODO: https://wanderinginn.com/2022/08/20/9-09-p/ filter vacation report
  - chapter_url: https://wanderinginn.com/2022/09/10/9-15-vm/
    selector_type: css
    selector: p:-soup-contains("I am on break until the 20th of September!")
  - chapter_url: https://wanderinginn.com/2022/09/28/interlude-the-great-race/
    selector_type: css
    selector: p:-soup-contains("I wrote an essay because")
  - chapter_url: https://wanderinginn.com/2022/09/28/interlude-the-great-race/
    selector_type: css
    selector: p:-soup-contains("https://wanderinginn.com/essay-ais-and-the-future-of-writing/")
  - chapter_url: https://wanderinginn.com/2022/10/09/9-19/
    selector_type: css
    selector: p:-soup-contains("Andrew Rowe has come out with Book 4 in his series, Arcane Ascension!")
  - chapter_url: https://wanderinginn.com/2022/10/16/interlude-death-and-stitches/
    selector_type: css
    selector: p:-soup-contains("The Merch Store has Halloween-themed merchandise!")
  - chapter_url: https://wanderinginn.com/2022/10/16/interlude-death-and-stitches/
    selector_type: css
    selector: p a img
  - chapter_url: https://wanderinginn.com/2022/10/16/interlude-death-and-stitches/
    selector_type: css
    selector: p:-soup-contains("Book 8, Blood of Liscor, is coming out on Audible and as an e-book soon!")
  - chapter_url: https://wanderinginn.com/2022/10/16/interlude-death-and-stitches/
    selector_type: css
    selector: p:-soup-contains("The author is on break until October 25!")
  - chapter_url: https://wanderinginn.com/2022/10/26/9-21/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn survey has a statistics page!")
  - chapter_url: https://wanderinginn.com/2022/10/30/9-22-gn/
    selector_type: css
    selector: p:-soup-contains("Trigger Warning")
  - chapter_url: https://wanderinginn.com/2022/11/02/9-23-ggggggggg/
    selector_type: css
    selector: p:-soup-contains("Trigger Warning")
  - chapter_url: https://wanderinginn.com/2022/11/05/9-24/
    selector_type: css
    selector: p:-soup-contains("Author’s Disclaimer:")
  - chapter_url: https://wanderinginn.com/2022/11/16/interlude-adventurers-pt-3/
    selector_type: css
    selector: p:-soup-contains("Join a free gift raffle for Blood of Liscor, the next book on Audible!")
  - chapter_url: https://wanderinginn.com/2022/11/16/interlude-adventurers-pt-3/
    selector_type: css
    selector: p:-soup-contains("The author is on break until November 26th!")
  - chapter_url: https://wanderinginn.com/2022/11/27/9-25/
    selector_type: css
    selector: p:-soup-contains("The Merch Store is having a Black Friday sale!")
  - chapter_url: https://wanderinginn.com/2022/11/27/9-25/
    selector_type: css
    selector: p:-soup-contains("The Blood of Liscor, Book 8 is out on Audible and as an e-book!")
  - chapter_url: https://wanderinginn.com/2022/11/29/9-26-f/
    selector_type: css
    selector: p:-soup-contains("Gravesong is out now on Yonder!")
  - chapter_url: https://wanderinginn.com/2022/12/04/9-27-rc/
    selector_type: css
    selector: p:-soup-contains("Gravesong is out now on Yonder!")
  - chapter_url: https://wanderinginn.com/2022/12/18/9-29/
    selector_type: css
    selector: p:-soup-contains("This chapter is 45,000+ words long.")
  - chapter_url: https://wanderinginn.com/2022/12/21/9-30/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn store is having a Solstice sale!")
  - chapter_url: https://wanderinginn.com/2022/12/21/9-30/
    selector_type: css
    selector: p:-soup-contains("Trial of the Alchemist, a mystery-fantasy by Trevor Melanson")
  - chapter_url: https://wanderinginn.com/2022/12/25/9-31/
    selector_type: css
    selector: p:-soup-contains("The author is on break until January 17th!")
  - chapter_url: https://wanderinginn.com/2023/01/31/9-35-o/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is putting out an open-call for a book marketer/publicist!")
  - chapter_url: https://wanderinginn.com/2023/02/04/9-36-ho/
    selector_type: css
    selector: p:-soup-contains("I am taking two updates off to finish my rewrite of Volume 1.")
  - chapter_url: https://wanderinginn.com/2023/02/15/9-37-ho/
    selector_type: css
    selector: p:-soup-contains("I am on my monthly break!")
  - chapter_url: https://wanderinginn.com/2023/03/01/9-38-tv-pt-2/
    selector_type: css
    selector: p:-soup-contains("The writing notes for 9.38 TV can be found here.")
  - chapter_url: https://wanderinginn.com/2023/03/05/interlude-beginnings/
    selector_type: css
    selector: p:-soup-contains("Volume 1 has been completely rewritten and is up now.")
  - chapter_url: https://wanderinginn.com/2023/03/12/9-40-gg/
    selector_type: css
    selector: p:-soup-contains("A huge thank you to the medical readers who contributed to this chapter!")
  - chapter_url: https://wanderinginn.com/2023/03/19/interlude-brewing-sariants/
    selector_type: css
    selector: p:-soup-contains("The author is on break before they explode of tiredness.")
  - chapter_url: https://wanderinginn.com/2023/03/29/interlude-the-spitoon/
    selector_type: css
    selector: p:-soup-contains("Casualfarmer author of Beware of Chicken")
  - chapter_url: https://wanderinginn.com/2023/04/01/interlude-stories/
    selector_type: css
    selector: p:-soup-contains("Pale Lights, a new story by the author of A Practical Guide to Evil")
  - chapter_url: https://wanderinginn.com/2023/04/01/interlude-stories/
    selector_type: css
    selector: p:-soup-contains("I am on break next update to write Gravesong")
  - chapter_url: https://wanderinginn.com/2023/04/01/interlude-stories/
    selector_type: css
    selector: p:-soup-contains("I am no longer taking chem-reader submissions.")
  - chapter_url: https://wanderinginn.com/2023/04/01/interlude-stories/
    selector_type: css
    selector: p:-soup-contains("Tears of Liscor, Book 9 of The Wandering Inn is up for pre-order")
  - chapter_url: https://wanderinginn.com/2023/04/12/9-41-pt-2/
    selector_type: css
    selector: p:-soup-contains("Podium Audio is featuring fanworks for the Tears of Liscor launch!")
  - chapter_url: https://wanderinginn.com/2023/04/16/interlude-levels/
    selector_type: css
    selector: p:-soup-contains("I am taking a break until April 29th!")
  - chapter_url: https://wanderinginn.com/2023/04/30/9-41-pt-3/
    selector_type: css
    selector: p:-soup-contains("I am on break for the month of May to write a novel.")
  - chapter_url: https://wanderinginn.com/2023/04/30/9-41-pt-3/
    selector_type: css
    selector: p:-soup-contains("The Tears of Liscor is out on Audible.")
  - chapter_url: https://wanderinginn.com/2023/04/30/9-41-pt-3/
    selector_type: css
    selector: p:-soup-contains("The store has also launched a series of keychains!")
  - chapter_url: https://wanderinginn.com/2023/06/04/interlude-trade-and-travel/
    selector_type: css
    selector: p:-soup-contains("MelasD, a fellow author and reader of The Wandering Inn")
  - chapter_url: https://wanderinginn.com/2023/06/04/interlude-trade-and-travel/
    selector_type: css
    selector: 'p:-soup-contains("Foreword: I have returned.")'
  - chapter_url: https://wanderinginn.com/2023/06/04/interlude-trade-and-travel/
    selector_type: css
    selector: p:-soup-contains("It is a day of prophecy.")
  - chapter_url: https://wanderinginn.com/2023/06/04/interlude-trade-and-travel/
    selector_type: css
    selector: p:-soup-contains("In Batman’s The Dark Knight Returns")
  - chapter_url: https://wanderinginn.com/2023/06/04/interlude-trade-and-travel/
    selector_type: css
    selector: p:-soup-contains("When I went to sleep, I woke up to find a huge carpenter ant crawling on me")
  - chapter_url: https://wanderinginn.com/2023/06/04/interlude-trade-and-travel/
    selector_type: css
    selector: p:-soup-contains("I am Antman.")
  - chapter_url: https://wanderinginn.com/2023/06/04/interlude-trade-and-travel/
    selector_type: css
    selector: p:-soup-contains("Nothing’s changed. Everything’s changed. It’s good to be back.")
  - chapter_url: https://wanderinginn.com/2023/06/07/9-43-l/
    selector_type: css
    selector: p:-soup-contains("I am releasing a chapter a day rather than one every 3-4 days")
  - chapter_url: https://wanderinginn.com/2023/06/08/9-44-p/
    selector_type: css
    selector: p:-soup-contains("I am releasing a chapter a day rather than one every 3-4 days")
  - chapter_url: https://wanderinginn.com/2023/06/10/9-45-gt/
    selector_type: css
    selector: p:-soup-contains("I am releasing a chapter a day rather than one every 3-4 days")
  - chapter_url: https://wanderinginn.com/2023/06/10/9-46-s/
    selector_type: css
    selector: p:-soup-contains("I am releasing a chapter a day rather than one every 3-4 days")
  - chapter_url: https://wanderinginn.com/2023/06/13/9-47-u/
    selector_type: css
    selector: p:-soup-contains("I am releasing a chapter a day rather than one every 3-4 days")
  - chapter_url: https://wanderinginn.com/2023/06/16/9-48-btiprljmwvrv/
    selector_type: css
    selector: p:-soup-contains("I am taking my monthly writing break until the 27th!")
  - chapter_url: https://wanderinginn.com/2023/06/16/9-48-btiprljmwvrv/
    selector_type: css
    selector: p:-soup-contains("Trevor Melanson has released a new series")
  - chapter_url: https://wanderinginn.com/2023/07/16/9-54-c/
    selector_type: css
    selector: p:-soup-contains("I am on break to finish writing Gravesong, Book 2")
  - chapter_url: https://wanderinginn.com/2023/07/16/9-54-c/
    selector_type: css
    selector: p:-soup-contains("My friend Quill has released a new book")
  - chapter_url: https://wanderinginn.com/2023/07/16/9-54-c/
    selector_type: css
    selector: p:-soup-contains("https://www.amazon.com")
  - chapter_url: https://wanderinginn.com/2023/07/16/9-54-c/
    selector_type: css
    selector: p:-soup-contains("Martel has only one wish")
  - chapter_url: https://wanderinginn.com/2023/08/30/9-55-pt-1/
    selector_type: css
    selector: p:-soup-contains("I am taking a 1-update hiatus")
  - chapter_url: https://wanderinginn.com/2023/08/30/9-55-pt-1/
    selector_type: css
    selector: p:-soup-contains("The Wind Runner, Book 10 of The Wandering Inn, is now available for pre-order on Audible and Kindle")
  - chapter_url: https://wanderinginn.com/2023/08/30/9-55-pt-2/
    selector_type: css
    selector: p:-soup-contains("We have a new shirt featuring the Horns of Hammerad on the merch store")
  - chapter_url: https://wanderinginn.com/2023/09/05/9-56/
    selector_type: css
    selector: p:-soup-contains("See the link here for details")
  - chapter_url: https://wanderinginn.com/2023/09/05/9-56/
    selector_type: css
    selector: p:-soup-contains("We have a new shirt featuring the Horns of Hammerad on the merch store")
  - chapter_url: https://wanderinginn.com/2023/09/09/9-57-b/
    selector_type: css
    selector: p:-soup-contains("The site needs a part-time webmaster")
  - chapter_url: https://wanderinginn.com/2023/09/12/9-58-o/
    selector_type: css
    selector: p:-soup-contains("There will be official TWI Mugs available soon")
  - chapter_url: https://wanderinginn.com/2023/09/12/9-58-o/
    selector_type: css
    selector: p:-soup-contains("When you win you can curl up on a chair in front of the fire")
  - chapter_url: https://wanderinginn.com/2023/09/12/9-58-o/
    selector_type: css
    selector: p:-soup-contains("Alexander Wales, author of Worth the Candle")
  - chapter_url: https://wanderinginn.com/2023/09/12/9-58-o/
    selector_type: css
    selector: p:-soup-contains("We have temporary issues with the commenting system")
  - chapter_url: https://wanderinginn.com/2023/09/17/9-59-o/
    selector_type: css
    selector: p:-soup-contains("I am on break until October 7th for Patreon readers")
  - chapter_url: https://wanderinginn.com/2023/09/17/9-59-o/
    selector_type: css
    selector: p:-soup-contains("Book 10 of The Wandering Inn, The Wind Runner, is out now!")
  - chapter_url: https://wanderinginn.com/2023/10/15/9-60/
    selector_type: css
    selector: p:-soup-contains("Selkie Myth, author of Beneath the Dragoneye Moons")
  - chapter_url: https://wanderinginn.com/2023/10/15/9-60/
    selector_type: css
    selector: p:-soup-contains("Art by fuyudust!")
  - chapter_url: https://wanderinginn.com/2023/10/15/9-60/
    selector_type: css
    selector: p:has(a)
  - chapter_url: https://wanderinginn.com/2023/10/17/9-61-g/
    selector_type: css
    selector: p:-soup-contains("MelasD is launching a Kickstarter for their book, Salvos!")
  - chapter_url: https://wanderinginn.com/2023/10/28/9-64-bh/
    selector_type: css
    selector: p:-soup-contains("Book 11, The Titan of Baleros is out now")
  - chapter_url: https://wanderinginn.com/2023/11/19/9-65/
    selector_type: css
    selector: p:-soup-contains("Book 11, The Titan of Baleros is out now")
  - chapter_url: https://wanderinginn.com/2023/11/19/9-65/
    selector_type: css
    selector: p:-soup-contains("The Wandering Inn is running the annual survey")
  - chapter_url: https://wanderinginn.com/2023/11/19/9-65/
    selector_type: css
    selector: p:-soup-contains("We are selling a poster of the Winter’s Eve Solstice artwork")
  - chapter_url: https://wanderinginn.com/2023/11/26/9-67-pt-1/
    selector_type: css
    selector: p:-soup-contains("This chapter has been split into two parts for easier readability")
  - chapter_url: https://wanderinginn.com/2023/11/26/9-67-pt-1/
    selector_type: css
    selector: p:-soup-contains("Given the length of this chapter, I will skip an update on Tuesday")
  - chapter_url: https://wanderinginn.com/2023/11/28/9-68/
    selector_type: css
    selector: p:-soup-contains("This chapter has a trigger warning for disturbing content")
  - chapter_url: https://wanderinginn.com/2023/11/28/9-68/
    selector_type: css
    selector: p:-soup-contains("A trigger-free version of the chapter")
  - chapter_url: https://wanderinginn.com/2023/11/28/9-68/
    selector_type: css
    selector: p:-soup-contains("A summary of the chapter has also been written here")
  - chapter_url: https://wanderinginn.com/2023/11/28/9-68/
    selector_type: css
    selector: p:-soup-contains("I released this chapter early so I will take until the 5th to release the next chapter")

