startUrl: https://wanderinginn.com/2020/01/19/7-00/
endUrl: https://wanderinginn.com/2020/12/23/solstice-pt-9/
metadata:
  title: The Wandering Inn - Volume 7
  author: pirateaba
  description: |
    "No killing Goblins."

    So reads the sign outside of the Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.

    It's a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a dragon. She doesn't belong in a place where monster attacks are a fact of life, and where humans are one species among many. But she must adapt to her new life. Or die.

    In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no [Warrior], no [Mage]. Erin Solstice runs an inn.

    She's an [Innkeeper].
selectors:
  titleElement: .entry-title
  contentElement: .entry-content
  nextChapterElement: .entry-content a:-soup-contains("Next Chapter")
  cutOffElement:
    - p:-soup-contains("After Chapter Thoughts:")
    - p:-soup-contains("Author’s Note:")
    - p:-soup-contains("Author’s Notes:")
    - p:has(a:-soup-contains("Previous Chapter"))
    - p:has(a:-soup-contains("Next Chapter"))
substitutions:
  - selectorType: text
    selector: <p>—-</p>
    replaceWith: <hr/>
  - selectorType: text
    selector: <p>—–</p>
    replaceWith: <hr/>
  - chapterUrl: https://wanderinginn.com/2020/01/22/7-01/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/01/26/7-02/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/03/29/7-15-r/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/03/31/7-16-l/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/04/12/7-17-s/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/04/19/interlude-strategists-at-sea-pt-1/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/04/22/interlude-strategists-at-sea-pt-2/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/05/13/7-23-lm/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/05/24/7-24/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/05/27/7-25/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/06/14/7-29-b/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/06/28/7-31/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/07/01/interlude-a-meeting-of-druids/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/07/05/7-32-d/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/07/12/7-34-c/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/07/15/7-35-c/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/07/19/7-36-c/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/07/29/7-37/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/07/29/7-37/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/08/05/7-39-a/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/08/08/interlude-carriages-and-conversations/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/08/11/7-40-er/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/08/12/interlude-food-and-growth/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/09/02/7-43-g/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/09/13/7-46-k/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/09/13/7-46-k/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/09/13/7-46-k/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/09/20/7-48-k/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/09/23/7-49/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/10/07/7-50/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/10/25/7-55-e/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/11/04/interlude-saliss-the-adventurer/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/11/08/7-56/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/11/25/interlude-the-tribes-of-izril/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/12/06/interlude-the-innkeepers-knight/
    selectorType: css
    selector: p:first-of-type
  - chapterUrl: https://wanderinginn.com/2020/12/23/solstice-pt-3/
    selectorType: css
    selector: p:first-of-type
