start_url: https://wanderinginn.com/2024/02/04/10-00-l/
crawler_module: WanderingInnPatreonCrawler
metadata:
  title: The Wandering Inn - Volume 10
  author: pirateaba
  description: |
    "No killing Goblins."

    So reads the sign outside of the Wandering Inn, a small building run by a young woman named Erin Solstice. She serves pasta with sausage, blue fruit juice, and dead acid flies on request. And she comes from another world. Ours.

    It's a bad day when Erin finds herself transported to a fantastical world and nearly gets eaten by a dragon. She doesn't belong in a place where monster attacks are a fact of life, and where humans are one species among many. But she must adapt to her new life. Or die.

    In a dangerous world where magic is real and people can level up and gain classes, Erin Solstice must battle somewhat evil Goblins, deadly Rock Crabs, and hungry [Necromancers]. She is no [Warrior], no [Mage]. Erin Solstice runs an inn.

    She's an [Innkeeper].
selectors:
  title_element: .entry-title
  content_element: .entry-content
  next_chapter_element: span.nav-next a[rel=next]
  cut_off_element:
    - p:-soup-contains("After Chapter Thoughts:")
    - p:-soup-contains("After Chapter Notes:")
    - p:-soup-contains("Author Call:")
    - p:-soup-contains("Author’s Story:")
    - p:-soup-contains("Author’s Note:")
    - p:-soup-contains("Author’s Notes:")
    - p:-soup-contains("Author’s Thoughts:")
    - p:-soup-contains("Author’s Note")
    - p:-soup-contains("Authors’ Note:")
    # These two should alwas be at the end of the list!
    - p:has(a:-soup-contains("Previous Chapter"))
    - p:has(a:-soup-contains("Next Chapter"))
style: |
  @font-face {
    font-family: "Charm";
    src: url("./charm.ttf") format("truetype");
    font-weight: 400;
    font-style: normal;
    font-display: swap;
  }
  .mrsha-write {
      font-family: "Charm", cursive;
      font-size: 110%;
      letter-spacing: 0.12rem;
  }
substitutions:
  - selector_type: text
    selector: <p>—-</p>
    replace_with: <hr/>
  - selector_type: text
    selector: <p>—–</p>
    replace_with: <hr/>
  - selector_type: text
    selector: <p>——</p>
    replace_with: <hr/>
  - chapter_url: https://wanderinginn.com/2024/02/07/10-01-l/
    selector_type: css
    selector: p:-soup-contains("Will Wight is Kickstarting an animation for their Cradle series!")
  - chapter_url: https://wanderinginn.com/2024/02/21/10-05/
    selector_type: css
    selector: p:-soup-contains("I am on break till March 5th!")
  - chapter_url: https://wanderinginn.com/2024/03/06/10-06/
    selector_type: css
    selector: p:-soup-contains("Read this blog about important changes to the update schedule of The Wandering Inn.")
  - chapter_url: https://wanderinginn.com/2024/03/10/10-07/
    selector_type: css
    selector: p:-soup-contains("Book 12, The Witch of Webs, is now up for pre-order on Kindle and Amazon")
  - chapter_url: https://wanderinginn.com/2024/03/10/10-07/
    selector_type: css
    selector: p:-soup-contains("Amazon:")
  - chapter_url: https://wanderinginn.com/2024/03/10/10-07/
    selector_type: css
    selector: p:-soup-contains("Audible:")
